export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EMPLOYEES_LOADING = "EMPLOYEES_LOADING";
export const SIGNIN_EMPLOYEE = "SIGNIN_EMPLOYEE";
export const LOGOUT_EMPLOYEE = "LOGOUT_EMPLOYEE";
