export const GET_FINANCES = "GET_FINANCES";
export const GET_FINANCE = "GET_FINANCE";
export const UPDATE_FINANCE = "UPDATE_FINANCE";
export const ADD_FINANCE = "ADD_FINANCE";
export const DELETE_FINANCE = "DELETE_FINANCE";
export const FINANCES_LOADING = "FINANCES_LOADING";
export const SIGNIN_FINANCE = "SIGNIN_FINANCE";
export const LOGOUT_FINANCE = "LOGOUT_FINANCE";
